# Generated by Django 4.2.6 on 2024-06-14 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('direccion_sede', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección de la Sede')),
                ('telefono_empresa', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de la Empresa')),
                ('telefono_empresa2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de la Empresa')),
                ('numero_identificacion_fiscal', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Identificación Fiscal')),
                ('tipo_empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Empresa')),
                ('sector_empresa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sector de la Empresa')),
                ('numero_empleados', models.IntegerField(blank=True, null=True, verbose_name='Número de Empleados')),
                ('descripcion_empresa', models.TextField(blank=True, null=True, verbose_name='Descripción de la Empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
