# Generated by Django 5.0.3 on 2024-06-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_proyecto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(max_length=15)),
                ('contacto', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='imagen/')),
            ],
        ),
    ]
