# Generated by Django 4.1.5 on 2024-06-10 21:07

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_proyecto_nom_aprendiz'),  # Reemplaza 'tu_app_name' y 'tu_migration_anterior' con tus nombres reales
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='nom_aprendiz',
        ),
    ]