# Generated by Django 4.1.5 on 2024-06-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_rename_texto_comentario_contenido_and_more'),
        ('task1', '0005_auto_20240610_1607'),
    ]

    operations = [
    ]
