# Generated by Django 4.1.5 on 2024-06-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0007_proyecto_nom_aprendiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen1',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen4',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='categoria',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='contacto',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(upload_to='proyectos/'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nom_aprendiz',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='nom_proyecto',
            field=models.CharField(max_length=255),
        ),
    ]
