# Generated by Django 4.1.5 on 2024-06-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0008_proyecto_imagen1_proyecto_imagen2_proyecto_imagen3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='colaboradores',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tecnologias',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tiempo_desarrollo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
